apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-api
spec:
  # Modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: qr-api
  template:
    metadata:
      labels:
        app: qr-api
    # Modify container details according to your case
    spec:
      containers:
      - name: qr-api
        image: hmnomaan0/devops-qr-code-api:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: qr-api-service
spec:
  type: LoadBalancer
  selector:
    app: qr-api     
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000